### ISSUE TITLE
DFP is not displayed

### ISSUE THREAD

**Issue by milkovsky** [BurdaMagazinOrg/module-ad_entity#19]
Using beta11.
Ads are not displayed for "Default HTML view for a DFP tag".
https://github.com/BurdaMagazinOrg/module-ad_entity/pull/18

**Comment by mxhCodes** [comment]
Thanks for the report & PR. Could you give a little bit more detailed description about the given problem?

I'm currently not sure why

```
googletag.display(ad_tag[0]);
```
is causing the problem and that
```
googletag.display(ad_tag.data('id'));
```
would solve it, since both ways should be valid as seen in the documentation of DFP regards googletag.display(div):


> Either the ID of the div element containing the ad slot or the div element itself. If a div element is provided, it must have an 'id' attribute which matches the ID passed intogoogletag.defineSlot().


I've seen drastically reduced ad displays on my development environments, which are running under different domains than production environments. But I couldn't determine which change in the refactored code causes the display problem. Even my stage environment, which has not been updated to beta11 and is still equivalent to my (still working?) production environment, yet now behaves exactly the same as my dev environment running with beta11. It's confusing.

**Comment by milkovsky** [comment]
Unfortunately I can not provide any helpful details.
I am using just DFP Ads provider, only locally for now.
I have tried beta11, it did not work: I do not see any error, the Ads are just not displayed.
beta10 worked for me; after some debugging, I figured out that this change broke Ads display for me.

**Comment by mxhCodes** [comment]
I'm unable to identify the source of the problem. To make the ads at least working on your environment again, I'm just including your PR into the next commit, and will create a new release today.

**Comment by milkovsky** [comment]
wow, thanks a lot!
